### ISSUE TITLE
Removes NTE In Tablist

### ISSUE THREAD

**Issue by Myth1c4lYT** [MarcinWieczorek/NovaGuilds#101]
I Have The NTE Plugin Installed And Vault And Everything But Instead Of Showing The NTE Prefix It Shows The Guild Tag. How Do I Fix This.

**Comment by MarcinWieczorek** [comment]
Please provide a screenshot

**Comment by MarcinWieczorek** [comment]
Check if setting `tagapi` to false in the config solves your issue. Removing ALL scoreboards from the server/world might be necessary

**Comment by Myth1c4lYT** [comment]
fixed. thanks.
