### ISSUE TITLE
Found bugs

### ISSUE THREAD

**Issue by Kennar** [MarcinWieczorek/NovaGuilds#18]
Wersja pod Claudron:
 Znalezione Błędy:
- Po stworzeniu Gildii nie ma punktów.
- Błąd po wpisaniu /g home set poza terenem gildii : http://hastebin.com/jeyufafelo.rb
- Brak pobieranych pieniędzy za kupiony effect.
- Gdy mam gm 1 i stawiam lub niszczę coś na obsydianie : http://hastebin.com/yuduzotoli.avrasm
  
  Propozycje:
- Działające kolory tagów nad głową.
- Przeniesienie stanu przejmowania na Chat lub scoreboards.
- Nowa ranga "Zastępca Gildii".
- Powiększanie terenu Gildii.
- Ważność Gildii.
- Zmienianie statusu pvp w gildii.
- Ochrona dla nowych gildii (np:24 Godziny)

**Comment by artur9010** [comment]
Dziekujemy za zgloszenie bledow. Postaramy sie jak najszybciej to poprawic.

**Comment by MarcinWieczorek** [comment]
DziękujeMY, postaraMY XD
Artur, dzięki że uważasz się za autora, serio.

Home poprawione
Powiedz coś więcej o tym obsi, bo nie bardzo mogę sobie wyobrazić o co chodziło... Spróbuj sprowokować ten błąd jeszcze raz, i sprawdź kiedy występuje.
Przejmowanie chyba przeniosłem już, w zależności od tego czy jest włączone BarAPI powinno działać.
Reszta TODO

Dzięki! ;)

**Comment by Kennar** [comment]
Z tym obsem jest tak, że jak jestem na randze OP + ranga z \* i mam włączonego gm, i gdy chcę coś postawić lub zniszczyć na obsydianie, chodzi oczywiście o obsydian, który tworzy się po założeniu Gildii.
Póżniej postaram się wysłać jakieś logi lub coś.

**Comment by artur9010** [comment]
Hmmm... sprawdzalem u siebie i nie ma takich problemow (z obsem)

Wersja serwera, lista pluginow, wersja javy. Możesz podać?

**Comment by MarcinWieczorek** [comment]
java7
Cauldron 1.7.10 (build na Cauldrona, pewnie najnowszy który jest na liście tej mojej)

Trochę się dziwię, bo błąd z obsem to bullshit, nie mogłoby coś takiego wystąpić. Pewnie sypnął RegionManager a dalej RegionInteractListener i dlatego takie błędy. Zrobiłem metody sprawdzające gildie i regiony, więc jak coś to powinno już nie być takich błędów, chyba że się zrobi lewy region podczas gdy serwer jest uruchomiony, to trzeba wyłapać i zgłosić tutaj ;P

PS:
Jakbyś mógł dawać te issues bardziej rozrzucone, w sensie osobno to byłbym wdzięczny ^^
Łatwiej ogarnąć

**Comment by artur9010** [comment]
Nie ciebie sie pytalem XD

**Comment by MarcinWieczorek** [comment]
ale wiem czego używa :P

**Comment by MarcinWieczorek** [comment]
Co było do naprawienia to naprawione, co było do dodania to dodane. Zamykam.
