### ISSUE TITLE
Required items' data won't be recognized

### ISSUE THREAD

**Issue by MarcinWieczorek** [MarcinWieczorek/NovaGuilds#20]
Using items with set data byte doesn't make any difference to ItemStackUtils' methods.
This applies to items like colored wool etc.

Anyone got time to fix that?

**Comment by svens-uk** [comment]
Assuming someone hasn't forgotten. P close the issue, I'll fork it and then submit a pull request at some point.

**Comment by svens-uk** [comment]
to close*

**Comment by MarcinWieczorek** [comment]
Thanks. I won't close it, just wait for you to commit changes with a message 'closes #20' and pull request.

Are you CaughtException from Minecolt?

**Comment by svens-uk** [comment]
Yeah, I'll go and fork it now

**Comment by MarcinWieczorek** [comment]
Please pull, made a mistake, commited something I haven't even compiled...
