### ISSUE TITLE
Propozycja nowej listy buildów do pobrania.

### ISSUE THREAD

**Issue by artur9010** [MarcinWieczorek/NovaGuilds#22]
https://novaguildsdl-artur9010.c9.io

**Comment by artur9010** [comment]
Jak coś, tło lekko do loga nie pasuje (kolorystycznie) ;)

edit: fix'd

**Comment by MarcinWieczorek** [comment]
Kocham Cię misiu, ale tło ;p
BIERE TO

**Comment by artur9010** [comment]
Zaraz ci to w tara spakuje i podeśle XD

**Comment by MarcinWieczorek** [comment]
OK

**Comment by artur9010** [comment]
https://novaguildsdl-artur9010.c9.io/ctrl.tar.gz
Wiem ujowo spakowane, ale jest XD
w /home/ubuntu/workspace masz pliki
kopiujesz wszystko z tego folderu po za .c9, ctrl.tar.gz, php.ini i readme ;)

**Comment by artur9010** [comment]
A i generowanie listy plikow musisz sobie sam napisac XD 
Nie mam dostepu do twojej bazy :P

**Comment by MarcinWieczorek** [comment]
http://novaguilds.marcin.co/download/

**Comment by MarcinWieczorek** [comment]
Na plikach to mam, nie chce mi się na bazie robić

**Comment by artur9010** [comment]
Ty to na podstawie nazwy pliku czy jak?

**Comment by artur9010** [comment]
Czy ręcznie to wpisujesz wszystko XD

**Comment by MarcinWieczorek** [comment]
ta

**Comment by MarcinWieczorek** [comment]
w sensie po nazwie pliku wszystkie dane i data modyfikacji

**Comment by MarcinWieczorek** [comment]
Download latest stable/beta/dev build? 
Ja takich ładnych przycisków w bootstapie nie robię jak Ty
