### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kennar** [MarcinWieczorek/NovaGuilds#26]
Silnik Claudron:
- Podwójne wiadomości po wpisaniu /g home, oraz podczas przerywania teleportacji
- Nie wczytujące się sojuesz po reloadzie
- Żle działający odstęp między gildiami
  
  I coś jeszcze, ale nie pamiętam :D

**Comment by MarcinWieczorek** [comment]
1. Naprawione
2. Naprawione
3. Poprawione, w miarę działa

Dzięki ;)
