### ISSUE TITLE
Błedy

### ISSUE THREAD

**Issue by Kennar** [MarcinWieczorek/NovaGuilds#28]
Znalezione błedy Claudron:
- Po wpisaniu /nga g purge pisze: This command is not available.
- Hologram w skarbcu jest o 1 kratkę wysunięty w kierunku "Z"
- Pod komendą /gg są 3 tabliczki

Propozycje: 
- Możliwość ustawienia na jakim świecie plugin ma nie działać

**Comment by MarcinWieczorek** [comment]
Powiedz mi jeszcze czy ujemne są te koordynaty Z czy dodatnie

purge jeszcze nie zrobione

**Comment by Kennar** [comment]
Ujemne :)

**Comment by MarcinWieczorek** [comment]
Hologram w skarbcu jest o 1 kratkę wysunięty w kierunku "Z"
Poprawione

**Comment by MarcinWieczorek** [comment]
Propozycję biorę pod uwagę, zostanie to dodane.

Tabliczki też już poprawione, dzięki, zamykam.
PS: Na przyszłość dawaj każdą propozycję/buga w osobnym issues ;)
