### ISSUE TITLE
Bug z usuwaniem Gildii

### ISSUE THREAD

**Issue by Piotr-Pie** [MarcinWieczorek/NovaGuilds#35]
Posiadam wersję spigota 1.8.7
Instalowałem różne twoje wersje NovaGuilds i tylko bez błędów w Consoli działają wersje build 25 i 26, ale jest problem z usuwaniem gildii..

1). Teran po Gildii zostaje, nie jest usuwany z regionu.
2). Jak założyciel wpisze /rozwiaz, to wyskakuje informacja że opuścił gildię, a nie jest rozwiązana.

UWAGA!!
Ale jak przeładuje plugin NovaGuilds, to region znika i jest ok...

To tylko tyle błędów, jakie na razie znalazłem na 1.8.7

Pozdrawiam i życzę powodzenia z dalszym rozwojem pluginu...

Edit:
Ale po podłączeniu Bazy mysql, bug z regionem znika.

**Comment by MarcinWieczorek** [comment]
Raczej w starsze buildy to się nie baw. Każdy nowszy powinien działać zarówno na 1.8, jak i na 1.7.
MySQL raczej działa spoko, system zapisu na plikach może być ostro zbugowany, tym bardziej SQLite.
Czy nawet z MySQL błąd nr. 2 nadal występuje?

Dziękuję za pomoc, postaram się to w miarę szybko naprawić.

**Comment by MarcinWieczorek** [comment]
Bug z regionami naprawiony w 5c0e7fdf0399b6fbfb02eff1f7302c6d56311c0c

Edit:
Nie zauważam żadnego błędu związanego z rozwiązywaniem gildii, opisz dokładniej.
