### ISSUE TITLE
Plugin nie czyta configu przy uruchomieniu

### ISSUE THREAD

**Issue by kamileks999** [MarcinWieczorek/NovaGuilds#41]
Cześć,
Od kilku dni testuje twój plugin, jednak od początku mam z nim problem.
Twój plugin (#28) jest zdecydowanie najlepszym z pluginów na gildie na moją wersję serwera - PaperSpigot 1.8.8. Po skonfigurowaniu pluginu zauważyłem, że po restarcie plugin nie wczytuje zmian z config.yml takich jak wersja językowa itp. Rzeczy te są wczytywany tylko po użyciu komendy /nga reload.
Prosiłbym o pomoc w naprawieniu tego, ponieważ lepszego pluginu aktualnie nie znalazłem :laughing: .
Pozdrawiam,
kamileks999

**Comment by MarcinWieczorek** [comment]
Po pierwsze build 29 został wydany jakąś godzinę temu, po drugie jakieś logi, config, więcej info proszę, bo na razie trudno mi sobie wyobrazić co to może być. 
Pozdrawiam Marcin Wieczorek

**Comment by kamileks999** [comment]
W wersji 29. błąd przestał występować.
Dziękuję za pomoc :+1:

**Comment by MarcinWieczorek** [comment]
Już wiem co to było. Masz Essentials po angielsku i Ci się ładuje automatycznie angielskie tłumaczenie. /nga reload wczytuje pliki pomijając Essentials ;)
