### ISSUE TITLE
Nowe tabele w mysql

### ISSUE THREAD

**Issue by artur9010** [MarcinWieczorek/NovaGuilds#5]
U graczy:
- points (default 1000)
- kills (default 0)
- deaths (default 0)

Gdy gracz padnie, +1 do deaths
oraz +1 do kills dla osoby ktora ta osobe zabila
-5 do points osoby zabitej
+10 do points osoby zabijajacej

**Comment by MarcinWieczorek** [comment]
NovaGuilds nie przewiduje punktów dla graczy, tylko dla gildii.

**Comment by artur9010** [comment]
-,-

**Comment by artur9010** [comment]
Bo powiem rabusowi ze pomagac nie chcesz!1@!1111111oneoneoneonejedenjedenjeden

**Comment by artur9010** [comment]
No to poprosze punkciki :>

**Comment by MarcinWieczorek** [comment]
Zrób mi mavena to napiszę :*

**Comment by artur9010** [comment]
A... i przenies regiony do tej samej tabelii co gildie, latwiej bedzie :)

**Comment by artur9010** [comment]
Rano zrobie

**Comment by artur9010** [comment]
#17

**Comment by MarcinWieczorek** [comment]
Będę dziś w domu to napiszę

**Comment by MarcinWieczorek** [comment]
Done!
