### ISSUE TITLE
Komenda /gg nie działa

### ISSUE THREAD

**Issue by kamileks999** [MarcinWieczorek/NovaGuilds#50]
Witam ponownie, :laughing:
Po głębszych testach pluginu (już jako gracz) wykryłem błąd związany z komendą /gg.
Po wpisaniu komendy /gg wyskakuje biała wiadomość /guildmenu, nie otwiera się menu ani po wpisaniu obu tych komend.
W poniższym screenie jest pokazana ta sytuacja "w realu". Serwer pracuje pod PaperSpigotem 1.8.8, maszyna posiada Javę 8. W logach nie ma żadnych błędów.
Z wyrazami szacunku,
kamileks999
![Screen](https://cloud.githubusercontent.com/assets/16462592/12144411/be70206a-b487-11e5-9b3a-53594919333d.png)

**Comment by MarcinWieczorek** [comment]
Poprawione już dawno, ale chyba błąd wkradł się do wersji 29.
Mogę spróbować zrobić łatkę. Aktualny stan kodu jest dosyć niepewny. Dodany został system rang w gildii który nie jest jeszcze skończony. 
W jakim stopniu potrafisz posługiwać się gitem i mavenem?

**Comment by MarcinWieczorek** [comment]
Zapisać jako np 29ggpatch.sh, zmienić chmod na 777, odpalić.
Potrzebny jest git oraz Maven ;)
[29ggpatch.zip](https://github.com/MarcinWieczorek/NovaGuilds/files/79929/29ggpatch.zip)

``` bash
echo "Cloning NovaGuilds..."
git clone https://github.com/MarcinWieczorek/NovaGuilds.git

echo "Resetting HEAD to 29'th release..."
cd "NovaGuilds/"
git reset --hard 40786e4

echo "Downloading patch..."
cd ".."
wget https://github.com/MarcinWieczorek/NovaGuilds/commit/2bacd9fde444babac58c069e7cd9d019cc912d61.patch

echo "Applying patch..."
cd "NovaGuilds/"
git am --signoff < ../2bacd9fde444babac58c069e7cd9d019cc912d61.patch

echo "Building project..."
mvn clean install

echo "Copying the jar..."
cp "target/NovaGuilds-29.jar" "../NovaGuilds.jar"

echo "Done!"
```

**Comment by kamileks999** [comment]
Niestety po odpaleniu skryptu i wgraniu nowego pliku .jar na serwer nadal występuje problem :/

**Comment by MarcinWieczorek** [comment]
Daj log ze skryptu. 
Nie odpalaj dwa razy bez czyszczenia folderu

**Comment by kamileks999** [comment]
Log z 22ggpatch.sh

Cloning NovaGuilds...
Cloning into 'NovaGuilds'...
remote: Counting objects: 10166, done.
remote: Compressing objects: 100% (428/428), done.
remote: Total 10166 (delta 196), reused 0 (delta 0), pack-reused 9711
Receiving objects: 100% (10166/10166), 2.01 MiB | 2.75 MiB/s, done.
Resolving deltas: 100% (5112/5112), done.
Checking connectivity... done.
Resetting HEAD to 29'th release...
HEAD is now at 40786e4 Teleporting in main thread (closes #40)
Downloading patch...
--2016-01-08 20:02:57--  https://github.com/MarcinWieczorek/NovaGuilds/commit/2bacd9fde444babac58c069e7cd9d019cc912d61.patch
Translacja github.com (github.com)... 192.30.252.128
Łączenie się z github.com (github.com)|192.30.252.128|:443... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: nieznana [text/plain]
Zapis do: `2bacd9fde444babac58c069e7cd9d019cc912d61.patch'

2bacd9fde444babac58c069e7cd9d019cc912d61.     [ <=>                                                                                    ]   1,07K  --.-KB/s   w  0s

2016-01-08 20:02:58 (9,04 MB/s) - zapisano `2bacd9fde444babac58c069e7cd9d019cc912d61.patch' [1095]

Applying patch...

**\* Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for git@kamileks999.eu) not allowed
You need to set your committer info first
Building project...
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building NovaGuilds 29
[INFO] ------------------------------------------------------------------------
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://ci.drtshock.net/plugin/repository/everything/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.oc.tc/content/groups/public/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://ci.frostcast.net/plugin/repository/everything/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml (2 KB at 1.6 KB/sec)
Downloading: http://repo.novaguilds.pl/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.kitteh.org/content/groups/public/org/spigotmc/spigot-api/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.oc.tc/content/groups/public/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: http://ci.frostcast.net/plugin/repository/everything/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.novaguilds.pl/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.kitteh.org/content/groups/public/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 1.4 KB/sec)
Downloaded: https://repo.oc.tc/content/groups/public/net/md-5/bungeecord-chat/1.8-SNAPSHOT/maven-metadata.xml (770 B at 0.4 KB/sec)
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.oc.tc/content/groups/public/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloading: http://ci.frostcast.net/plugin/repository/everything/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.novaguilds.pl/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.kitteh.org/content/groups/public/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://repo.oc.tc/content/groups/public/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml (600 B at 1.2 KB/sec)
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-parent/1.8-SNAPSHOT/maven-metadata.xml (602 B at 2.0 KB/sec)
Downloading: https://ci.drtshock.net/plugin/repository/everything/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.oc.tc/content/groups/public/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://ci.frostcast.net/plugin/repository/everything/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.novaguilds.pl/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.kitteh.org/content/groups/public/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://repo.oc.tc/content/groups/public/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml (778 B at 1.7 KB/sec)
Downloading: https://ci.drtshock.net/plugin/repository/everything/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.oc.tc/content/groups/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml (2 KB at 11.9 KB/sec)
Downloading: http://ci.frostcast.net/plugin/repository/everything/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.novaguilds.pl/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.kitteh.org/content/groups/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml (2 KB at 9.2 KB/sec)
Downloading: https://ci.drtshock.net/plugin/repository/everything/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
Downloading: https://repo.oc.tc/content/groups/public/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
Downloading: http://ci.frostcast.net/plugin/repository/everything/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
Downloading: http://repo.novaguilds.pl/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
Downloading: http://repo.kitteh.org/content/groups/public/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
Downloading: https://repo.maven.apache.org/maven2/com/gmail/filoghost/holographicdisplays.api/2.1.3/holographicdisplays.api-2.1.3.pom
[WARNING] The POM for com.gmail.filoghost:holographicdisplays.api:jar:2.1.3 is missing, no dependency information available
Downloading: https://ci.drtshock.net/plugin/repository/everything/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.oc.tc/content/groups/public/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml
Downloading: http://ci.frostcast.net/plugin/repository/everything/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.novaguilds.pl/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.kitteh.org/content/groups/public/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml
Downloaded: http://repo.kitteh.org/content/groups/public/org/kitteh/VanishNoPacket/3.19.2-SNAPSHOT/maven-metadata.xml (777 B at 2.4 KB/sec)
[WARNING] The POM for org.kitteh:VanishNoPacket:jar:3.19.2-20140621.151001-3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Downloading: https://ci.drtshock.net/plugin/repository/everything/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
Downloading: https://repo.oc.tc/content/groups/public/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
Downloading: http://nexus.theyeticave.net/content/repositories/pub_releases/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
Downloading: http://ci.frostcast.net/plugin/repository/everything/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
Downloading: http://repo.novaguilds.pl/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
Downloading: http://repo.kitteh.org/content/groups/public/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/bukkit/craftbukkit/1.7.10-R0.1/craftbukkit-1.7.10-R0.1.pom
[WARNING] The POM for org.bukkit:craftbukkit:jar:1.7.10-R0.1 is missing, no dependency information available
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ NovaGuilds ---
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ NovaGuilds ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ NovaGuilds ---
[INFO] Compiling 154 source files to /home/git/NovaGuilds/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ NovaGuilds ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/git/NovaGuilds/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ NovaGuilds ---
[INFO] Compiling 6 source files to /home/git/NovaGuilds/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ NovaGuilds ---
[INFO] Surefire report directory: /home/git/NovaGuilds/target/surefire-reports

---

##  T E S T S

Running co.marcin.novaguilds.yaml.YamlParseTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.636 sec
Running co.marcin.novaguilds.yaml.YamlEnumTest

Testing config enums...
All values are present in Config enum

Testing message enums...
All values are present in Message enum
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec
Running co.marcin.novaguilds.yaml.YamlIncompleteTranslationTest

## Testing lang files for missing keys...

Testing lang: pl-pl

## Result: No missing keys

Testing lang: de-de

## Result: No missing keys

Testing lang: zh-cn
Result: No missing keys
Result: No missing keys
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.117 sec
Running co.marcin.novaguilds.PermissionEnumTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec
Running co.marcin.novaguilds.GuildPermissionEnumTest
Looking for GuildPermission values not present in Message enum
Nothing is missing here.
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
Running co.marcin.novaguilds.VersionTest
Current version: 29
Dev version: 29
Stable version: 29
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.227 sec

Results :

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ NovaGuilds ---
[INFO] Building jar: /home/git/NovaGuilds/target/NovaGuilds-29.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ NovaGuilds ---
[INFO] Installing /home/git/NovaGuilds/target/NovaGuilds-29.jar to /home/git/.m2/repository/co/marcin/NovaGuilds/29/NovaGuilds-29.jar
[INFO] Installing /home/git/NovaGuilds/pom.xml to /home/git/.m2/repository/co/marcin/NovaGuilds/29/NovaGuilds-29.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.147s
[INFO] Finished at: Fri Jan 08 20:03:29 CET 2016
[INFO] Final Memory: 30M/73M
[INFO] ------------------------------------------------------------------------
Copying the jar...
Done!

**Comment by MarcinWieczorek** [comment]
Czytanie nie boli ;)
To załatwi sprawę, wpisz to i uruchom jeszcze raz.

``````
*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.```
``````
