### ISSUE TITLE
Error nie pozwala używać pluginu

### ISSUE THREAD

**Issue by RafalKedziora** [MarcinWieczorek/NovaGuilds#58]
Witam,
  Sprawa wygląda tak, że podczas uruchamiania pluginu występuje pierwszy bug, który blokuje wszystko później.
Wersja silnika: Spigot 1.7-1.8
Wersja javy: 7

Logi i config:
http://pastebin.com/eetPwqfN

**Comment by RafalKedziora** [comment]
Sprawdzałem przed chwilą, że wersja #30 działa

**Comment by MarcinWieczorek** [comment]
Wybacz mi brak reakcji, powiem tylko że zajmuję się między innymi tym właśnie błędem.

**Comment by RafalKedziora** [comment]
Nie ma problemu. Czekam z niecierpliwością.

**Comment by MarcinWieczorek** [comment]
Skompilujesz sobie czy podesłać jar? ;)

**Comment by RafalKedziora** [comment]
Wolałbym jar, jeśli nie robi ci to większego problemu. :)

**Comment by MarcinWieczorek** [comment]
http://repo.novaguilds.pl/co/marcin/novaguilds/34-SNAPSHOT/

**Comment by RafalKedziora** [comment]
Dzięki ;)

**Comment by MarcinWieczorek** [comment]
np. daj znać czy działa

**Comment by RafalKedziora** [comment]
Plugin NovaGuilds v34 has failed to register events for class co.marcin.novaguilds.listener.RegionInteractListener because org/bukkit/event/player/PlayerArmorStandManipulateEvent does not exist.

W logach coś takiego znalazłem

**Comment by RafalKedziora** [comment]
Tak to nie ma żadnych problemów. Gildie się tworzą i usuwają bez problemu
Nie wiem jak będzie przy większej ilości graczy, bo akurat tworzymy nową edycję serwera, ale jeśli coś się popsuje to dam znać.

**Comment by MarcinWieczorek** [comment]
Te eventy to się na 1.7 nie rejestrują po prostu i coś takiego wywala, bo nie ma armor standów. Jest to raczej niegroźne.
Dzięki za pomoc

**Comment by RafalKedziora** [comment]
To ja dziękuję. Twoja pomoc ratuje mnie i mój serwer. FunnyGuilds jest trochę... Jakby to powiedzieć wypalone i posiada mnóstwo bugów, a twój plugin jest teraz jedyny w swoim rodzaju, jest aktualizowany i mam nadzieję, że będzie cały czas rozwijany, Jak będziesz miał kiedyś chwilę wolnego to możesz jeszcze plugin na logowanie napisać, bo authme ostatnio też ma jakieś problemy i coś dziwnego się dzieje przy większej ilości osób na serwerze. 
 Jeszcze raz wielkie dzięki i powodzenia w rozwijaniu tego zacnego projektu. :)

**Comment by MarcinWieczorek** [comment]
Dzięki.
Chętnie pomogę w rozwoju serwera, więc możesz do mnie napisać email lub na gg/skype.
Co do logowania to raczej wątpię.

**Comment by RafalKedziora** [comment]
http://pastebin.com/GNug89Bj
Nowy error :)
