### ISSUE TITLE
Gdy admin usuwa gildie, gracze nie traca gildii.

### ISSUE THREAD

**Issue by artur9010** [MarcinWieczorek/NovaGuilds#6]
Rozwiazalem gildie innego gracza.
(/nga g gildia abandon)
Ale jej czlonkowie dalej sa w tej gildii (wg. bazy)

http://screenshot.sh/ofh7ioXQcRfGv

Przy okazji propozycja: przy starcie serwera przeleciec wszystkich graczy i jezeli sa w gildii ktora nie istnieje, wywalic ich z niej.
I moze zastapic nazwe gildii jej id? Wtedy byla by mozliwa edycja tagu i nazwy bez wiekszego problemu :) A przy okazji taka opcja okazalaby sie moze wydajniejsza?

**Comment by MarcinWieczorek** [comment]
Rozwiązałeś moją gildię?! Jak mogłeś *unsub
Ściągnij se normalnego builda, nawet tego na Cauldrona bo będzie działał

**Comment by artur9010** [comment]
Pobralem pre2 wersji 11

**Comment by artur9010** [comment]
Build na cauldrona pobrany

**Comment by artur9010** [comment]
Po wylaczeniu serwera, wpisy sie poprawily.

**Comment by MarcinWieczorek** [comment]
Gościu, dane się nie zapisują w biegu. Tylko dodawanie i usuwanie rekordów.
Wystarczy /nga save

**Comment by artur9010** [comment]
"Tylko"
czyli to czego jest prawie najwiecej

**Comment by MarcinWieczorek** [comment]
Jeden powód i będą inserty/delety przy zapisywaniu wszystkiego

**Comment by artur9010** [comment]
Nie trzeba
