### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by RafalKedziora** [MarcinWieczorek/NovaGuilds#62]
Witam, 
Wracam z kolejnym pytaniem. chciałbym zmienić wersję javy na moim serwerze z 7 na 8.
Na stronie twojego pluginu zauważyłem, że twój plugin jest na javie 7. Czy to znaczy, że nie będzie obsługiwał 8?

**Comment by MarcinWieczorek** [comment]
Wszystko będzie działać bez zarzutu. Problem pojawia się przy cofaniu wersji, np do javy 6.

**Comment by RafalKedziora** [comment]
Która java jest według ciebie bardziej wydajna?

**Comment by MarcinWieczorek** [comment]
Najnowsza.
