### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by RafalKedziora** [MarcinWieczorek/NovaGuilds#63]
Jako, że jest to plugin moim zdaniem bardzo rozbudowany, w wielu przypadkach używany na serwerach z dropem, to moim zdaniem powinieneś wprowadzić do tego pluginu generatory stone.

**Comment by RafalKedziora** [comment]
Przy okazji, zmieniam ten prefix z [NovaGuilds] na inny to mi nie działa i dalej zostaje ten podstawowy. O co chodzi?

**Comment by MarcinWieczorek** [comment]
Od tego są pluginy na generatory stone. 

Aby pozbyć się nazwy pluginu należy sobie go samemu skompilować. 
Ostatnio zacząłem a raczej zacznę walkę z binarnymi plikami NG w internecie.

**Comment by RafalKedziora** [comment]
A gdzie znajdę rozkompilowaną wersję 34? 
Czy mam sam sobie rozkompliować?

**Comment by MarcinWieczorek** [comment]
Rozkompilowaną? Co żeś wymyślił znowu? Przecież źródło jest tutaj, na githubie.

**Comment by MarcinWieczorek** [comment]
Masz w Readme jak skompilować, jak coś to pisz. Craftbukita musisz sobie sam skompilować bo dystrybucja binarek jest nielegalna, bo jest objęty prawami autorskimi. Z BuildTools będziesz miał
