### ISSUE TITLE
Punkty

### ISSUE THREAD

**Issue by RafalKedziora** [MarcinWieczorek/NovaGuilds#66]
Witaj, nie wiem czemu, ale punkty mi nie działają

**Comment by RafalKedziora** [comment]
Mam startowe 1000, a gracze mają 0

**Comment by MarcinWieczorek** [comment]
Logi, config itp

**Comment by RafalKedziora** [comment]
Dobra, ogarnąłem o co chodzi. Swoją drogą strasznie rozbudowany plugin co się chwali.
Ale dalej nie mogę znaleźć top graczy xd

**Comment by RafalKedziora** [comment]
Mam na myśli czy jest komenda na to ;)

**Comment by RafalKedziora** [comment]
/g top - Top gildii
Mi chodzi o top graczy

**Comment by MarcinWieczorek** [comment]
Nie ma. Możesz sobie napisać plugin na to.
