### ISSUE TITLE
1.9.2 TAB list tag issue

### ISSUE THREAD

**Issue by Craftaris** [MarcinWieczorek/NovaGuilds#67]
The plugin seem to works fine, but all the tags in the TAB list are not working

My config: http://hastebin.com/edoyofawid.yaml

**Comment by MarcinWieczorek** [comment]
Tags work fine for me on a clean setup. Please tell me how to reproduce the bug.

**Comment by MarcinWieczorek** [comment]
Do you use any plugin that messes around Scoreboards? It may be the cause.
