### ISSUE TITLE
Something wrong with take over the enemy guild

### ISSUE THREAD

**Issue by Martynza** [MarcinWieczorek/NovaGuilds#69]
At the Spigot 1.9.4 appears many errors (look here: http://wklej.to/8VomE). When we want to take over the enemy guild, plugin are showing us bossbar and nothing more are happend. As well as the tag before Nick does not work in essentials. On 1.9.2 version no errors in logs but still have the above errors.

**Comment by MarcinWieczorek** [comment]
YAML error has been fixed here: bc8eddf06e8775618d97ea1c8774774f182ae12a
SignGUI has been implemented in 37c1220f322da25cf66a77bf5192ba574070b9ef
