### ISSUE TITLE
Problem z utratą leadera Gildii

### ISSUE THREAD

**Issue by pjorun** [MarcinWieczorek/NovaGuilds#70]
Dość często się zdarza, że leader Gildii przestaje nim być. Traci TAG Gildii, nie może nic budować na terenie Gildii, jednak gdy inni członkowie sprawdzają kto należy do członków Gildii to w dalszym ciągu pokazuję, że on jest Leaderem. Problem się naprawia po przeładowaniu pluginu.

Dodaje logi:
https://gist.github.com/pjorun/1c80fba9a015aaefcfae1d116907c6d6

**Comment by MarcinWieczorek** [comment]
Problem powinien zniknąć razem z wersją 38
