### ISSUE TITLE
Conflict with Commandbook

### ISSUE THREAD

**Issue by JohOply** [MarcinWieczorek/NovaGuilds#76]
Hi guy!

I'm trying your plugin and some commands doesn't work: they display the CommandBook's error message.

http://i.imgur.com/jsFm5YW.png
http://i.imgur.com/WdWX19E.png

List of menu's commands i've seen: home, guild's name, guild's tag, sethome, turn pvp, toggle invitation, buy life, buy slot.

All this commands work if Commandbook is disabled and seems work if I use manual command (/g...) :)

**Comment by MarcinWieczorek** [comment]
Thanks for reporting this.
I've found the solution already. I started rewriting GUI a few days ago so I can't commit the fix. I hope to get it finished soon.

**Comment by JohOply** [comment]
Okay it's nice, thank you! :)

**Comment by MarcinWieczorek** [comment]
This is not solved yet.
