### ISSUE TITLE
Tablista - zmienne

### ISSUE THREAD

**Issue by ghost** [MarcinWieczorek/NovaGuilds#79]
Witam,
Piszę, ponieważ nie mogę nigdzie znaleźć zmiennych do tablisty do Pana pluginu jest zapisane w configu, że powinny się one znajdować na stronie pluginu, lecz przeszukałem strone, githuba itd. i nie znalazłem. Mógłby Pan podesłać pełną lista zmiennych?

**Comment by MarcinWieczorek** [comment]
Jest w wiki.
