### ISSUE TITLE
Error when I create a guild

### ISSUE THREAD

**Issue by Daxxas** [MarcinWieczorek/NovaGuilds#85]
Hello, 

I have an error when I try to create a guild : https://hastebin.com/ronutecowu.sql

My config.yml : https://hastebin.com/ivomorurey.coffeescript

I hope you are still on this plugin :S

**Comment by MarcinWieczorek** [comment]
Thank you for reaching out. First of all please download a snapshot of version 40 (you can find it at http://novaguilds.pl)
Then paste (sprunge.us preferably or any *raw* paste) the whole log, as the startup is very important.

**Comment by Daxxas** [comment]
It's fixed with release 40# !

Thanks you ! Does there is a changelog for it ? (Just for the new features, not the bug fix)

**Comment by MarcinWieczorek** [comment]
The changelog for 40 will be filled on the release.
