### ISSUE TITLE
The autoregion is gone in the latest dev build

### ISSUE THREAD

**Issue by Daxxas** [MarcinWieczorek/NovaGuilds#89]
Hello,

I compared my old config and a newly generated one, and the "autoregion: true" is not there anymore !
Can I add it manually in the config ? Where could I do it ?

**Comment by Daxxas** [comment]
I still have an error when using the build 39, still when I create a guild : 
https://hastebin.com/ihihobogek.sql

**Comment by Daxxas** [comment]
I've added the `autoregion: false` myself, and it changes nothing ;(
Here is my config.yml : https://hastebin.com/axoxinuhad.php
I use the version ; #40 (39222b3)

**Comment by MarcinWieczorek** [comment]
Is has been removed in 3069e6a8fde30f86010f5a225821e5f18ffee78b. Please change the automatic region size to 0 for each group in order to disable it.
