### ISSUE TITLE
TAG for chat

### ISSUE THREAD

**Issue by ArhamR** [MarcinWieczorek/NovaGuilds#94]
hi, i need help with the guilds plugin the tag thing in chat is not working i even put {TAG} in the chat format in essentials but it is just empty and the players did set a tag when making the guild. server is running the plugin on 1.8.

Essentials config:
https://pastebin.com/5C7DXMEf

Nova guilds config:
https://pastebin.com/PvDVJut8

MC chat image:
https://cdn.discordapp.com/attachments/407349535745245185/429632217053134859/2018-03-31_15.23.45.png

**Comment by MarcinWieczorek** [comment]
Show me your permissions please.

**Comment by ArhamR** [comment]
https://pastebin.com/xxRSbU7C

**Comment by MarcinWieczorek** [comment]
Why don't you have any NovaGuilds' permissions set up? Aren't you trying it as OP?

**Comment by ArhamR** [comment]
Yes i did it as an OP

**Comment by MarcinWieczorek** [comment]
Then you have `novaguilds.chat.notag` permission which hides the tag.

**Comment by ArhamR** [comment]
its not just that when they do the guild create command it says internal server error for some reason or it says An error occurred randomly without doing a command


![](https://cdn.discordapp.com/attachments/380843129097551872/429681215998525450/unknown.png)

**Comment by MarcinWieczorek** [comment]
Give me the logs please.

**Comment by ArhamR** [comment]
[2018-03-31-4.log](https://github.com/MarcinWieczorek/NovaGuilds/files/1879852/2018-03-31-4.log)

**Comment by MarcinWieczorek** [comment]
Do not use `/reload`.

**Comment by ArhamR** [comment]
I never did tho

**Comment by ArhamR** [comment]
So how do I fix the Tag issue and the error issue, do I reinstall??

**Comment by MarcinWieczorek** [comment]
Remove the `novaguilds.chat.notag` permission (just don't use OP)
Download latest snapshot:
`http://repo.novaguilds.pl/co/marcin/novaguilds/40-SNAPSHOT/`
Upload the logs again if there's anything else.

**Comment by ArhamR** [comment]
Where do I place the snapshot?, I have never used one before, also I have a 1.7.10 server will that affect the Versio ni need to download?

**Comment by MarcinWieczorek** [comment]
It's just a jar, replace your NovaGuilds.jar in plugins with it. It does not affect the server as all newer versions are backward compatible. The tablist should work better too.

**Comment by MarcinWieczorek** [comment]
Is this issue still valid for you?
