### ISSUE TITLE
How to support PlaceholderAPI

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [MarcinWieczorek/NovaGuilds#95]
I tried to support the PlaceholderAPI, but I don't know how to return the guild name. It seems very difficult to find them in the source code.

**Comment by MarcinWieczorek** [comment]
Tell me what exactly are you trying to do. GuildManager and PlayerManager will help you to find player/guild object.

**Comment by GouLiGuoJiaNaive** [comment]
Thanks! I have successfully parsed out the variable

**Comment by MarcinWieczorek** [comment]
Are you going to post a patch? Placeholders were asked for in #93

**Comment by GouLiGuoJiaNaive** [comment]
I have uploaded it to ecloud and downloaded the patch using /papi ecloud download novaguilds

**Comment by MarcinWieczorek** [comment]
Ugh, git maybe?
